### ISSUE TITLE
Add new tag

### ISSUE THREAD

**Issue by georgekamel** [blmayer/awslambdarpc#5]
Hello, 
Thank you very much for this tool - it's immensely useful.

I am using `go install` to install the tool to my $GOPATH/bin folder, and doing so installs the latest tagged version (v1.0.0). However, v1.0.0 contains a bug related to the -e flag which leads to the error `error opening file: open : no such file or directory`. I notice that this bug is fixed in a later commit, so I am just wondering if you could add a new tag so that `go install` will work without having to supply a commit hash to it? Thanks.

**Comment by blmayer** [comment]
Thank you @georgekamel! It is great to hear this tool is helping developers. I will tag the latest commit.

**Comment by blmayer** [comment]
Tag done: https://github.com/blmayer/awslambdarpc/releases/tag/v1.0.1
